# Generated by CoffeeScript 1.7.1
module.exports = (grunt) ->
    'use strict'

    ect_links =
        local:
            css: '/static/css/common.css'
            js: [
                '/static/js/lib/angular.js'
                '/static/js/lib/angular-resource.js'
                '/static/js/lib/angular-route.js'
                '/static/js/lib/angular-sanitize.js'
                '/static/js/lib/ui-bootstrap-tpls-0.11.0.js'
                '/static/js/lib/ngDialog.js'
                '/static/js/common.js'
            ]
        deploy:
            css: '/static/css/common.min.css'
            js: ['/static/js/common.min.js']

    grunt.initConfig

        pkg: grunt.file.readJSON('package.json')

        coffee:
            compile:
                files: [
                    expand: true
                    cwd: 'static/js/'
                    src: ['**/*.coffee']
                    dest: 'static/js/'
                    ext: '.js'
                ]
                options:
                    bare: true
                    separator: 'linefeed'

        sass:
            options:
                style: 'expanded'
            dist:
                files:
                    'static/css/common.css': 'static/css/common.sass'

        autoprefixer:
            no_dest:
                src: 'static/css/common.css'

        cssmin:
            minify:
                expand: true
                cwd: 'static/css/'
                src: ['common.css']
                dest: 'static/css/'
                ext: '.min.css'

        uglify:
            options:
                mangle: false
            my_target:
                files:
                    'static/js/common.min.js': ['static/js/common.js']

        concat:
            deploy:
                src: [
                    'static/js/lib/angular.js'
                    'static/js/lib/angular-resource.js'
                    'static/js/lib/angular-route.js'
                    'static/js/lib/angular-sanitize.js'
                    'static/js/lib/ui-bootstrap-tpls-0.11.0.js'
                    'static/js/lib/ngDialog.js'
                    'static/js/common.js'
                ]
                dest: 'static/js/common.js'

        ect:
            options:
                root: 'template/templates'
            local:
                src: 'grunt-generated.haml.ect'
                dest: 'template/templates/grunt-generated.haml'
                variables:
                    css: ect_links.local.css
                    js: ect_links.local.js
            deploy:
                src: 'grunt-generated.haml.ect'
                dest: 'template/templates/grunt-generated.haml'
                variables:
                    css: ect_links.deploy.css
                    js: ect_links.deploy.js

        watch:
            html_files:
                files: 'template/templates/*.haml'
            css:
                files: [
                    'static/**/*.sass',
                    'static/**/*.scss',
                ]
                tasks: ['build-css']
            js:
                files: 'static/js/common.coffee'
                tasks: ['coffee']
            options:
                spawn: false
                livereload: true

        connect:
            site1:
                options:
                    port: 80,
                    hostname: 'ms.local' # set your using host for example'localhost'


    grunt.loadNpmTasks 'grunt-contrib-sass'
    grunt.loadNpmTasks 'grunt-contrib-watch'
    grunt.loadNpmTasks 'grunt-contrib-concat'
    grunt.loadNpmTasks 'grunt-contrib-coffee'
    grunt.loadNpmTasks 'grunt-contrib-clean'
    grunt.loadNpmTasks 'grunt-contrib-cssmin'
    grunt.loadNpmTasks 'grunt-contrib-uglify'
    grunt.loadNpmTasks 'grunt-ect'
    grunt.loadNpmTasks 'grunt-autoprefixer'

    grunt.registerTask 'build-css', [
        'sass'
        'autoprefixer'
    ]

    grunt.registerTask 'local', [
        'build-css'

        'coffee'

        'ect:local'
    ]
    grunt.registerTask 'deploy', [
        'build-css'
        'cssmin'

        'coffee'
        'concat'
        'uglify'

        'ect:deploy'
    ]
    grunt.registerTask 'default', ['local']
