# Generated by CoffeeScript 1.7.1
module.exports = (grunt) ->
    'use strict'


    ect_links =
        local:
            css: '/static/css/common.css'
            js: [
                '/static/js/lib/angular.js'
                '/static/js/lib/angular-resource.js'
                '/static/js/lib/angular-route.js'
                '/static/js/lib/angular-sanitize.js'
                '/static/js/lib/ui-bootstrap-tpls-0.11.0.js'
                '/static/js/lib/ngDialog.js'
                '/static/js/common.js'
            ]
        deploy:
            css: '/static/css/common.min.css'
            js: ['/static/js/common.js']

    grunt.initConfig


        pkg: grunt.file.readJSON('package.json')

        coffee:
            compile:
                files: [
                    expand: true
                    cwd: 'static-src/js/'
                    src: ['**/*.coffee']
                    dest: 'static/js/'
                    ext: '.js'
                ]
                options:
                    bare: true
                    separator: 'linefeed'

        sass:
            options:
                style: 'expanded'
            dist:
                files:
                    'static/css/common.css': 'static-src/css/common.sass'

        autoprefixer:
            no_dest:
                src: 'static/css/common.css'

        cssmin:
            minify:
                expand: true
                cwd: 'static/css/'
                src: ['common.css']
                dest: 'static/css/'
                ext: '.min.css'

        watch:
            files: ['static-src/css/common.sass']
            tasks: 'sass'


        concat:
            deploy:
                src: [
                    'static-src/js/lib/angular.js'
                    'static-src/js/lib/angular-resource.js'
                    'static-src/js/lib/angular-route.js'
                    'static-src/js/lib/angular-sanitize.js'
                    'static-src/js/lib/ui-bootstrap-tpls-0.11.0.js'
                    'static-src/js/lib/ngDialog.js'
                    'static-src/js/common.js'
                ]
                dest: 'static/js/common.js'

        clean:
            local: [
                'static/css/common.min.css'
            ]
            deploy: [
                # 'static/js/lib/angular.js'
                # 'static/js/lib/angular-resource.js'
                # 'static/js/lib/angular-route.js'
                # 'static/js/lib/angular-sanitize.js'
                # 'static/js/lib/ui-bootstrap-tpls-0.11.0.js'
                # 'static/js/lib/ngDialog.js'
                'static/css/common.css'
            ]



        ect:
            options:
                root: 'template/templates'
            local:
                src: 'grunt-generated.haml.ect'
                dest: 'template/templates/grunt-generated.haml'
                variables:{
                    css: ect_links.local.css
                    js: ect_links.local.js
                }
            deploy:
                src: 'grunt-generated.haml.ect'
                dest: 'template/templates/grunt-generated.haml'
                variables:{
                    css: ect_links.deploy.css
                    js: ect_links.deploy.js
                }


    grunt.loadNpmTasks 'grunt-contrib-sass'
    grunt.loadNpmTasks 'grunt-contrib-watch'
    grunt.loadNpmTasks 'grunt-contrib-concat'
    grunt.loadNpmTasks 'grunt-contrib-coffee'
    grunt.loadNpmTasks 'grunt-contrib-clean'
    grunt.loadNpmTasks 'grunt-contrib-cssmin'
    grunt.loadNpmTasks 'grunt-ect'
    grunt.loadNpmTasks 'grunt-autoprefixer'

    grunt.registerTask 'local', [
        'sass'
        'autoprefixer'
        'coffee'

        'ect:local'
        'clean:local'
    ]
    grunt.registerTask 'deploy', [
        'sass'
        'autoprefixer'
        'coffee'

        'cssmin'
        'concat'
        'ect:deploy'
        'clean:deploy'
    ]
    grunt.registerTask 'default', ['local']
